-- ============================================================
-- 003_seed_citizens.sql - 30 công dân mẫu (đã mã hóa AES-256-GCM)
-- ENCRYPTION_KEY: YWJjZGVmZ2hpamtsbW5vcHFyc3R1dnd4eXoxMjM0NTY=
-- ============================================================

INSERT INTO citizens (id,full_name,date_of_birth,gender,national_id,phone_number,email,permanent_address,religion,ethnicity,marital_status,province_code,district_code,ward_code,is_alive,created_at,updated_at)
VALUES (uuid_generate_v4(),'Nguyễn Văn An','1990-05-15','male','M4paQhPN8ZHkOMcmXignttOe2wS0xi26QrOd+capPdlETQe2Q3FhWA==','J9SckqN3Qxg1RiJqAdARMgncwzQze9uEAiFclWOdzlT+LDnGwfY=','z2O6Fzx0BugVxYR/o1v+zL4ZxAPnxS6DidyTVIXpnNlfGXvE6fsSVptUw0wjJJ2EPNIR','JOB4/LHdjUPB7WUtVHv4/z884nvHezZCJD6wVr5lPefNkFPPPQUqzmj5Wm0KKmiVXDpVgLE5WD3ukbb8fmU=','Phật giáo','Kinh','married','01','001','00001',true,NOW(),NOW()) ON CONFLICT DO NOTHING;
INSERT INTO citizens (id,full_name,date_of_birth,gender,national_id,phone_number,email,permanent_address,religion,ethnicity,marital_status,province_code,district_code,ward_code,is_alive,created_at,updated_at)
VALUES (uuid_generate_v4(),'Trần Thị Bình','1985-08-20','female','8eLwoNiJJqyCn9meByTEiI+YdeM9Tiwt9STBnMRADIsnz3bZiHIuSw==','lrnUgPhn3P+V7HpcZTWAbklJ747Lf+hBOFYoQIG3y5h4QjWpHCI=','3enzQoWKvXN62KpHKUyQbG2WuqJ0n5GxpCmq9NKuKgkUHdGAEjNAITAKespO03OLa0eq','QwVW8JXC0kNiqYZ89QhYBzNxv8k7K4n+WQvUMRQhT6NmlC5abPyqM/wVcWAQVLAzPbMm0XiwyDf1mUxtwgAgrjE=','Không','Kinh','single','01','001','00002',true,NOW(),NOW()) ON CONFLICT DO NOTHING;
INSERT INTO citizens (id,full_name,date_of_birth,gender,national_id,phone_number,email,permanent_address,religion,ethnicity,marital_status,province_code,district_code,ward_code,is_alive,created_at,updated_at)
VALUES (uuid_generate_v4(),'Lê Minh Cường','1978-03-10','male','obSKBBb2lNlDmYew01QcUN8SQcrMdeqc5bDs4wOqqVNRM/p1kc51yA==','fw/OE730yfKuq+LlmwQpnJfWdNyCfRr20H68sHIrYIwPGXOPmnI=','p3Uwo7JUo3jkcSl3SQSk86CxVr1rr/s0HeD1gxMXbANwVFmM3eaF0nKbrwB5ICl1JqrB','c2z8SsxSgqaFngtD0jcmYhQ42c9Es7tWN3DlInGORiLaM7WPpIrW8W71+vYREGhScE/A6lMrWnci5igU2RCiZg==','Không','Kinh','married','01','001','00003',true,NOW(),NOW()) ON CONFLICT DO NOTHING;
INSERT INTO citizens (id,full_name,date_of_birth,gender,national_id,phone_number,email,permanent_address,religion,ethnicity,marital_status,province_code,district_code,ward_code,is_alive,created_at,updated_at)
VALUES (uuid_generate_v4(),'Phạm Thị Duyên','1995-11-25','female','FnUvNkeleNJlz4LecLGQUluOygJuscHZcflOlmG78J7qqBPXsNZTkQ==','R1wIXivVXlxDCT7YRtTGm+miV6XzMTfb3n/T0N9wkpkG1KDUHvc=','F4vD4ANL4cZkP6rg8MtbqHpS12CImhPdvsieH3Wazb4IsNJ8Ud7ZgRKihdNsGSDAX3K4cA==','u0xzq9l2at3Hps4/3kz4b4OOfzAj6+DBAaE5RA67+8lPCTT1oWQPzRmmTDiMTUiz06D0SaQyAMKj7SBgTzk=','Thiên Chúa','Kinh','single','01','001','00001',true,NOW(),NOW()) ON CONFLICT DO NOTHING;
INSERT INTO citizens (id,full_name,date_of_birth,gender,national_id,phone_number,email,permanent_address,religion,ethnicity,marital_status,province_code,district_code,ward_code,is_alive,created_at,updated_at)
VALUES (uuid_generate_v4(),'Hoàng Văn Em','1960-07-04','male','zqvML37JHW30PtQzyT87vI69p+ubhRfEQbuYqBdXS0FpRwDwRdRfdw==','JppaYddttjBWLd2vKKUMk8AQrt8l+M0E2mih6IF0o8WPGEwEVXA=','clG8aruwGHvKA1Mo5IIrpMZLsaPC1UmiDFjzvFWLViuwBH0+V/Y/9TnTPxdHp33aW0I=','T/8MRGlHhEKhgCLR6mjxc+sa+nnJY8A8cq3xxnLJ0k5YhA2+bRlYw3KWcHFbOD3ExMT/jTWQfMSP0iwxO3WSHmU=','Không','Kinh','divorced','01','001','00002',true,NOW(),NOW()) ON CONFLICT DO NOTHING;
INSERT INTO citizens (id,full_name,date_of_birth,gender,national_id,phone_number,email,permanent_address,religion,ethnicity,marital_status,province_code,district_code,ward_code,is_alive,created_at,updated_at)
VALUES (uuid_generate_v4(),'Vũ Thị Phương','1988-02-14','female','+zRcDdmnyBdBMMOv6YSP4vCelyX9Mb6E7OCfwy/KuHubXrAVlXp28g==','bjjzH/rePyU2TVV8YJlq4sWv8gno7m8itn+RQWPo4NJzSKZmry0=','VEDIhPWc19CkORbR84KnEk/OwPdIhHw4CdW70uDhwL8HEZxNP29H5PrSvsmotO32gEdX','+rS1UZVoDXLlw8fiuKGx0MTONuGQIJonn/wJsqLsicvVB7QHLpyj/0AHlkLSJ+4JPFJXQtzJ/kArGFRH2qqq','Không','Kinh','married','01','002','00010',true,NOW(),NOW()) ON CONFLICT DO NOTHING;
INSERT INTO citizens (id,full_name,date_of_birth,gender,national_id,phone_number,email,permanent_address,religion,ethnicity,marital_status,province_code,district_code,ward_code,is_alive,created_at,updated_at)
VALUES (uuid_generate_v4(),'Đỗ Quang Hùng','1975-09-30','male','59TlnkpvJqTZpbrO13XMTEsOe6z7JbL40JWfzlKspCIWlhxOC5E+ZA==','CiskQPYEMJzPbkLyYbw85CrjeUZn92mpwaOmjxm143ymL0P2lns=','ATawy7Il5tvVi85Ln5QhmJt4KkrnHIbF8j1BNkYMLrD8a3X2ySQsq9dB1IcCQSdc3upx','0mC0syjFCMk2+j2oVDixS5TeYMWjZru2a/zo4FiBUIKMOuG7lSFHECy6cUqu+AJDY3Hz2m9mF9AkzBI=','Phật giáo','Kinh','married','01','002','00011',true,NOW(),NOW()) ON CONFLICT DO NOTHING;
INSERT INTO citizens (id,full_name,date_of_birth,gender,national_id,phone_number,email,permanent_address,religion,ethnicity,marital_status,province_code,district_code,ward_code,is_alive,created_at,updated_at)
VALUES (uuid_generate_v4(),'Ngô Thị Lan','1992-06-18','female','+0L/HrvDwl7+JU675/JTv7JZ/tE4PhXZc+KqMMvwS6r4yrcDqJkUjw==','69i3Ynh24wEhF+NvNDFp/UsOdhA4m/KFhKMXdIajl+tiNuh522w=','wZabFR5sP/kiAPUx2w0/9hFKGCTcREKvK+K70q1AyiBlwemq3wEPFjHrbqgZ1MekwQ==','XWuTkCHHt5y2tMbV0fFtOeDAS1A/i0K+KsSHJDjnS87K6P9PUsHJ2agnCd4D3u3uswELAXB9AhPJA93887w=','Không','Kinh','single','01','002','00010',true,NOW(),NOW()) ON CONFLICT DO NOTHING;
INSERT INTO citizens (id,full_name,date_of_birth,gender,national_id,phone_number,email,permanent_address,religion,ethnicity,marital_status,province_code,district_code,ward_code,is_alive,created_at,updated_at)
VALUES (uuid_generate_v4(),'Bùi Văn Mạnh','1965-12-01','male','A6DbiBEuPviC9Bm4XgbCUylrpZ3UXllnLjjZb0D4R9cCDbmAzItquw==','9NQyeydA2k+ldtXfKLkvfEfDrzhDv7g7qJS6LAyLZtAcb1pWeM8=','u6jWIC4rnpncDLtgKstiJNu7rvRx5WOzX8Y+oeSrHBmhBz+MNvI/yuXpJx/1YrzrADU=','1Yz+SeI5xTm32nMyYW6z2PLmeyIF0+Z3V3xBbe+sfki1FbcS6MVxTbBm2fNOqeYA8jGu8HBhZNobIuI=','Không','Kinh','widowed','01','002','00011',false,NOW(),NOW()) ON CONFLICT DO NOTHING;
INSERT INTO citizens (id,full_name,date_of_birth,gender,national_id,phone_number,email,permanent_address,religion,ethnicity,marital_status,province_code,district_code,ward_code,is_alive,created_at,updated_at)
VALUES (uuid_generate_v4(),'Đinh Thị Nga','2000-04-22','female','caKkC4hyAlZpZ54WMtKgo0SvTjfWsYRqpHo3b/16IrDLjR52a8q1Tw==','L+Ok72kYUM1Rx3Pn1OCfOpYe7MR7VW2+DEuiv+YAr1V6d4M8Lak=','L/4Y5RN8ZpM0veKarSYtl70SGY9Brn5xBzGOh89kJ7RPC24P1E6fRAsSocaH/HfXGug=','70K0OUFa9XH4qmmIbZCW/wkF+znLoiU+JTfniSL5DuChLQAfA+1KcNwn5EPa9n8Xr6POK8v9dreiX7vBP+Y=','Không','Kinh','single','01','002','00010',true,NOW(),NOW()) ON CONFLICT DO NOTHING;
INSERT INTO citizens (id,full_name,date_of_birth,gender,national_id,phone_number,email,permanent_address,religion,ethnicity,marital_status,province_code,district_code,ward_code,is_alive,created_at,updated_at)
VALUES (uuid_generate_v4(),'Lê Hoàng Cường','1975-12-01','male','IOiWqnDAPx7miYqJAdupLMbA+9PjUTLN2d3YrGJi/jRDgHbiGlFk9w==','WLYPuGIZw8zG+Zgrg7tJxRjgk33hL3g8ijNJ+gS2M4XVwX9dUvY=','Vv3ogrks4lGaAHNrYudt5rsFVrL4Tm3YyR6kmqqmTQZclYsmO9AibQtwEsZrYkXvO+ir6g==','o1P3+3jmayYdWAfEV0a3By+eDP/o9Ubx8u9aRzpB2JwQQGyCBVEE7iGHeiEpQ73C/EBDztysyB+4Y7+f','Thiên Chúa','Kinh','married','79','760','26734',true,NOW(),NOW()) ON CONFLICT DO NOTHING;
INSERT INTO citizens (id,full_name,date_of_birth,gender,national_id,phone_number,email,permanent_address,religion,ethnicity,marital_status,province_code,district_code,ward_code,is_alive,created_at,updated_at)
VALUES (uuid_generate_v4(),'Phạm Thị Dung','2000-03-08','female','CiNrMxZhPF5dUa/N4qvgmc+cQZds8G4fc8Ca95gyb7+hpYQsmBf3Tg==','7QbOtXwJ9KBf5IHdWeaVj20aO4OoUBwsj7EnTyNy4GOj8iL9nsk=','+NG4AIvuqN9jyilyM/LldRt7l2TZLUDhdRwk7NEUaSZ1eq+02d8FWUDD+aTQfy0TFImU','4/C9XLJSlTVFB3rvEpDHGZmZsbSr+aNJVMKMGT+J06Gn6pCHKI0HdOe7O4yAtcKuSK6RGj5gXVbZsh6JUg==','Không','Hoa','single','79','760','26736',true,NOW(),NOW()) ON CONFLICT DO NOTHING;
INSERT INTO citizens (id,full_name,date_of_birth,gender,national_id,phone_number,email,permanent_address,religion,ethnicity,marital_status,province_code,district_code,ward_code,is_alive,created_at,updated_at)
VALUES (uuid_generate_v4(),'Trương Văn Khoa','1983-07-19','male','UBdRPm1RtmsBiSPJQsga/f/j8hcAmCGiUfASSXGT8sXo/mPWSpo35Q==','e3veCMB0RaV06gyJKvCRHJkHtRjpHjLyFwtH4yjvLZYQRPpDsx8=','JwlC8xfBUtZC6dC3qkJQT+omLpSbKdt6amgixnvItHV2RAc4WV5slezuBViZh8H6JYjlmgw=','dicWrhkWKrJ/DjsJE/uhGUF4tuHnXfNhdzFmU/78n6KLQtE0V/g60YdOGERn53G6v7GlFtpCwZaosQW5UA==','Không','Kinh','married','79','760','26734',true,NOW(),NOW()) ON CONFLICT DO NOTHING;
INSERT INTO citizens (id,full_name,date_of_birth,gender,national_id,phone_number,email,permanent_address,religion,ethnicity,marital_status,province_code,district_code,ward_code,is_alive,created_at,updated_at)
VALUES (uuid_generate_v4(),'Lý Thị Mai','1991-10-05','female','tHEIwBog5XIGkPuGsahpiPSzSAdpyD4zl5rqcFc99XbmpuMctHovrw==','lvS8ETrJmeFmvruocwd4FNGsUh6VOps7MTIAM+Dsm34lV5FdluU=','spaXGc405tLgsE7jveO0gv49Cx3deuPaWusW8jDO2IHUJYsSxUduW7s+3P/8gakw','JTiZ5mR1bAFiLIeZ4gF+lrW+eoWdZwWwgZ2WIk2FXXrXZ1RR3k4BOdiu8KTQWcmTaB5ensT3erSqcqCp/l6a','Phật giáo','Hoa','single','79','760','26737',true,NOW(),NOW()) ON CONFLICT DO NOTHING;
INSERT INTO citizens (id,full_name,date_of_birth,gender,national_id,phone_number,email,permanent_address,religion,ethnicity,marital_status,province_code,district_code,ward_code,is_alive,created_at,updated_at)
VALUES (uuid_generate_v4(),'Huỳnh Văn Nam','1969-01-15','male','DDu2xmvRJe7YkTgAh8tzj7uB+mtQRycKSjtEp/PSLoBWjJFWw4/rkw==','Ix/h9iw5d+tJdvwSwJJKptEuoSBgP8v4FuQY3TbNJpfJrxb6o+Q=','IvsV2htrbzop5/uRnbDLU5L+kqmHwhOYwEkA08KukGcEXsxQ1SLIBZlBfPNr71Sm8nMA','lwSGTm/uDtJqhHcsd4eTydQxtprvT2ZQRti6UKoP3W69SU+bp5cxI6sm5GAwasYJ1YiffN1KvrrN9dvm1g==','Không','Kinh','divorced','79','760','26736',true,NOW(),NOW()) ON CONFLICT DO NOTHING;
INSERT INTO citizens (id,full_name,date_of_birth,gender,national_id,phone_number,email,permanent_address,religion,ethnicity,marital_status,province_code,district_code,ward_code,is_alive,created_at,updated_at)
VALUES (uuid_generate_v4(),'Nguyễn Thị Oanh','1998-08-28','female','PAuO+8bOaGXM/anWgdmbmmZKKVMChvvmDkRUZkNxqY2lo2qVcbK33A==','zqUYVHgek22CUP96gC+Zj8afpQh9lF8Xo3+ghFYp+ZBOdl95Hag=','aLtkLVoRCIMu7BP43cfjUlOcmGSv7TDPxw9cPgJm6i2/iqjz2GVZv3HfN9g0U7o4/Iro0lA=','6uQBibfHx/WMsRQb2PvB2RtdyPCKXOIM+u/As+2T3vQost0dolYtQ5O111tBu/ssZk9VYDGDTOh7fIT3xpuy','Thiên Chúa','Kinh','single','79','760','26737',true,NOW(),NOW()) ON CONFLICT DO NOTHING;
INSERT INTO citizens (id,full_name,date_of_birth,gender,national_id,phone_number,email,permanent_address,religion,ethnicity,marital_status,province_code,district_code,ward_code,is_alive,created_at,updated_at)
VALUES (uuid_generate_v4(),'Võ Văn Phú','1955-05-20','male','uZLs/T3Qh2CPEDDlACCIepgXVPj5xz93NwzSVAbKj4mrM+G5mwMySQ==','S+zK43yiF0PsdbUGJAc7Bx52aHm/iBU9SuumTZXZ84ab5JMJGfc=','6YYrfTTqSklZfFTKgWhWH/9dcfpBRz5mMdiXOBBQeakG3tPurarfblPdvfku/sk+','w34TZ+VvRu5t5nxT2ZAXehWmZGHkdx19Y2xztv1Hdv5cJk/Lrf5s9YGKsdAscgtMqm9WFEFPTQT6g7WY','Phật giáo','Kinh','married','79','760','26734',true,NOW(),NOW()) ON CONFLICT DO NOTHING;
INSERT INTO citizens (id,full_name,date_of_birth,gender,national_id,phone_number,email,permanent_address,religion,ethnicity,marital_status,province_code,district_code,ward_code,is_alive,created_at,updated_at)
VALUES (uuid_generate_v4(),'Cao Thị Quỳnh','1987-03-11','female','ufaLvCwsNJb/ndMbuHMWFDcYjqMwKIKFKx7OYC7UoreSuqYwwQkp+A==','j+Cf9kHUi7wIktXRCWkT4w36JbaaoagcdGvLOft0pdGnwgTYvOw=','Asvz7tdfI7BJtO3MkNR2rMf2QjPXz3WymY+jVxEoE82A+B2uYCbPzbCt+U/AL4BcZoM/','UVHj9qK8yy4qpRQMCGpVl2xIBKiavoJY/J8sZ8qsyCrrWoHeCskH1JkJPpsfYRcotz+JaEejlgZXjySSew==','Không','Kinh','married','79','760','26736',true,NOW(),NOW()) ON CONFLICT DO NOTHING;
INSERT INTO citizens (id,full_name,date_of_birth,gender,national_id,phone_number,email,permanent_address,religion,ethnicity,marital_status,province_code,district_code,ward_code,is_alive,created_at,updated_at)
VALUES (uuid_generate_v4(),'Võ Minh Đức','1960-07-22','male','i1fGoNw1LalzK1qXNdAqy4nFhZrdAl1GbfHc89bsrvbCl6WLGpSNvQ==','6UGDUoKnEqXdHycKe7aWBnT+sOE/5qcnGQ0ABiqolqbXUIZjMLQ=','darmcYX2ckQ8fHRKrtY9iZpzUt7OU1AOLmGlOwI/wPLDgdw0WkjYY/KnXIev3KcoEg==','VLxcal0Y4vLvOlHc3yJXi64w3mZ0frqy7TOwnClz45PlHUGlUR1ZCGWHlAoBQHD2v/xI+wGqrgScv/uz8E6SpcVjl1Hpyg==','Không','Kinh','divorced','48','490','20194',true,NOW(),NOW()) ON CONFLICT DO NOTHING;
INSERT INTO citizens (id,full_name,date_of_birth,gender,national_id,phone_number,email,permanent_address,religion,ethnicity,marital_status,province_code,district_code,ward_code,is_alive,created_at,updated_at)
VALUES (uuid_generate_v4(),'Phan Thị Hoa','1993-09-14','female','zcb30wPOTSJu/pJ5XhYscFeVGvUbGXfP8fc2EqiA/MJ2aWoyis8ULw==','DMS8Cpy+MJP0U7/v1JDHDFDhtDLb01r5WlSk1AWhkPVIcGD6zM4=','sKisPmCxxGdbifJJ/Irn2mKHedBsBAG8q+VkJrDg5cNLkGbqR+wLvHknqg0ZiAlQG6A=','ks9QJDBKOP+Luoq9aI98YBAINiKGh39lCWsDNQgwfUje4wuyjnyrVE+Oja2iVNLK1pn/Pyf15fff5Zzb92bOh3dXktSoIA==','Không','Kinh','single','48','490','20195',true,NOW(),NOW()) ON CONFLICT DO NOTHING;
INSERT INTO citizens (id,full_name,date_of_birth,gender,national_id,phone_number,email,permanent_address,religion,ethnicity,marital_status,province_code,district_code,ward_code,is_alive,created_at,updated_at)
VALUES (uuid_generate_v4(),'Lê Văn Inh','1980-11-03','male','AiCZgLBUqI9K0NgV6zWWKD+dKo0mKCpVbCythCDAtbXH/BXlMNnejA==','xWZJHkP2pb7C4FfAGRTdirf73B6baj9raWhrdNrFH4e1zQ5hWNk=','Ma3TcRtaUKHBNn6Q0wOa1jcI6zudexVQP+x2lsBb+KbZFgc00nFX651AUAaO8mem','Wg5sNlmD1I8HvcZc5IyXy98Kc3sZTVAKhgVwnzvbwHdeL6Tn6qf1YNyG3k3NwxzNMtyZLF69mwpb/g9veHw9r2HnOIYx+g==','Phật giáo','Kinh','married','48','490','20194',true,NOW(),NOW()) ON CONFLICT DO NOTHING;
INSERT INTO citizens (id,full_name,date_of_birth,gender,national_id,phone_number,email,permanent_address,religion,ethnicity,marital_status,province_code,district_code,ward_code,is_alive,created_at,updated_at)
VALUES (uuid_generate_v4(),'Trần Thị Kim','1970-04-16','female','WCk4WFtRyq1Bs2cD+IdqblqZMw1ZCTRZb9OepXQ2uC1jw9+A+a7MRQ==','/nzMHs+6cbAQ325C8JADef+vX2qYDa1qB6nMaozGIGWavQt4Ypg=','CanOljmDnoe6rYSY5gKwMkDdAjGepztSz4yoWGapu4tZVtjzXIQVWrloZMrU8rzfrEw=','goMZGgJjPOS5CYVlbQjuxlIjz63tTdHybBXP675NB7cRdOa/XXHQhdxgR+3oaPNNNCy0qLM=','Không','Kinh','widowed','48','491','20194',false,NOW(),NOW()) ON CONFLICT DO NOTHING;
INSERT INTO citizens (id,full_name,date_of_birth,gender,national_id,phone_number,email,permanent_address,religion,ethnicity,marital_status,province_code,district_code,ward_code,is_alive,created_at,updated_at)
VALUES (uuid_generate_v4(),'Nguyễn Văn Long','1996-06-25','male','iHpIHaO07kT0QxRu3oHleIdLCQk7Cx72AcqpTRK01gAy6G24zJFcsg==','9fzqYYJt+tDW8DyNCEeA74KgfBYOiKNpGF58qqBnLMgv7ILvbS8=','jkR2UrGHbo4V2mpUpmQJDYZ0DOb4gNJldzXMkDCi1z2hQXFw1xhQDTcYkpaIikltYd/rO4I=','/OFZ+yk2nfmgzC8hNmIWsbfCiAT69e0WHVMPgTVls6L8pyrpLaSsVoi4j/WCrf0ICGtH2qQTkX4xy8smFhd0PVRI+FZI4g==','Không','Kinh','single','48','490','20195',true,NOW(),NOW()) ON CONFLICT DO NOTHING;
INSERT INTO citizens (id,full_name,date_of_birth,gender,national_id,phone_number,email,permanent_address,religion,ethnicity,marital_status,province_code,district_code,ward_code,is_alive,created_at,updated_at)
VALUES (uuid_generate_v4(),'Nguyễn Thị Em','1945-01-10','female','IYHWm4g4Ho/walUA0kxYxsmfoG4j3A9vNwKtDEBlXv6Feh+MrzlbRQ==','n1jEqJZERq/3reEI5PiRE2SpD3uJzP7PdKx/YSWIkUSYSnHgfxg=','iF+lHYn8gAmHdzvOeYQtD9Ef0cCE0jC+0VIzSXuV6C/k7wCu78yxSojiq3h6e6uxjwA7','lUPgv+jCivta/7Ong33NDh7bXfYrMaw1BDE4nbwLSBLbPzw33VYYAzTcBmP2ly/nWmPlUy8QEaajjWcuwMwL','Phật giáo','Kinh','widowed','92','900','31150',false,NOW(),NOW()) ON CONFLICT DO NOTHING;
INSERT INTO citizens (id,full_name,date_of_birth,gender,national_id,phone_number,email,permanent_address,religion,ethnicity,marital_status,province_code,district_code,ward_code,is_alive,created_at,updated_at)
VALUES (uuid_generate_v4(),'Lê Văn Phong','1988-07-07','male','nbNK8U50tf8BLBJc9J4nun1z/ynUEpe0+jt8Q3U8dbOtgQ2siVDGjg==','qu74vP30iG/xeCgkTm+3uFURSo2YNi9uE8tcUxEJ+IFmZqiPK5A=','dlqyy/79Alf00xcJkC/c6oggPYWLocNshpWdIcluIV5xX4f0lSjaNcHMsRsGiWOEQGc=','XUcD6+aTZEZ2vBdByGh5kIBgKq0RgUIwaww7h5S41MhMiavIX8pNUjR5cLjuOOZC45qbqMc1wzeit5VSsqzrSaNUIzQ=','Không','Kinh','married','92','900','31151',true,NOW(),NOW()) ON CONFLICT DO NOTHING;
INSERT INTO citizens (id,full_name,date_of_birth,gender,national_id,phone_number,email,permanent_address,religion,ethnicity,marital_status,province_code,district_code,ward_code,is_alive,created_at,updated_at)
VALUES (uuid_generate_v4(),'Trần Thị Quyên','1975-02-19','female','RJ+S0M6kqKiIKnW105W7KFTYCja1dkBysYaW73suBgXgdxa/1ZBQ1Q==','ZjIOgqLg06YWWzVk6x1Z2vAfhnQfG3hn6ASLg9mSWSA6uGWlJnA=','YMDs7iKowiPg+DG2jL+q+wtzF18VHW50+fkGXvOPNGGFtfKRnkEtgUaYFWZ3++/FgRIP7w==','BxpowRV4QoTBevqDzu/7pUh/1Rf/G+K8HCokuvzBEMqLF8NKFCLzdNNfTRP2Qk1vxR0OtwHSPCc+j1DKo7Fq','Phật giáo','Kinh','married','92','900','31150',true,NOW(),NOW()) ON CONFLICT DO NOTHING;
INSERT INTO citizens (id,full_name,date_of_birth,gender,national_id,phone_number,email,permanent_address,religion,ethnicity,marital_status,province_code,district_code,ward_code,is_alive,created_at,updated_at)
VALUES (uuid_generate_v4(),'Phạm Văn Rạng','1990-12-30','male','MZr+umXk0bPS6ombBwB71hUMHMChxPeQP05O3od5NOobsmfzHCT4Ag==','3iEGL2a+n1bOs6+WLGd9Ys+wbbQ9hEIjdWORyj+SJEshsFMrPR8=','i9nQf/vVmH7Q5myz7KO32W/KzvmliZoYR6zlksxhklM+JEcT+T8Ho6jiq/qvgqdHd4Zq','pvbz00rHVyb7RVg+YmDIiRchCZv/apYwGz+ZkSTZH/uAdSp82K5IjvuOpc8v5yABSQ0PnZJ9MOVVNH+G5G9LMs7KZYw=','Không','Kinh','single','92','900','31151',true,NOW(),NOW()) ON CONFLICT DO NOTHING;
INSERT INTO citizens (id,full_name,date_of_birth,gender,national_id,phone_number,email,permanent_address,religion,ethnicity,marital_status,province_code,district_code,ward_code,is_alive,created_at,updated_at)
VALUES (uuid_generate_v4(),'Ngô Thị Sen','1962-08-08','female','fX99w6giGi0oBUFB4qAu7va7h9oofK1S0sgB7pg7QOaRGxFgaBb1bw==','fnHJmIwICEKE11GVk9cZ+3HG4ZGSwG+ommuAOxxPS4mjksyP1ms=','V1cta6m647lUq21J2tjXWPEkMRxC6ADT9sBdFVq74mch6P/dSAdZJZ+gccZdGWK82A==','rJtQAMCPcizoShlfhDZRPA+J67vM8zmSHNUjzAIhwCJzhm2sLtoaSb8iYAS7RZYmCzqX3koCytNzEUplDd02','Thiên Chúa','Khmer','divorced','92','900','31150',true,NOW(),NOW()) ON CONFLICT DO NOTHING;
INSERT INTO citizens (id,full_name,date_of_birth,gender,national_id,phone_number,email,permanent_address,religion,ethnicity,marital_status,province_code,district_code,ward_code,is_alive,created_at,updated_at)
VALUES (uuid_generate_v4(),'Huỳnh Văn Tài','1999-05-05','male','PvKz4yAjFRZ3x+rGjySO/TmqV4WqB5HAnRTX8dmGVxLu0eL3A2oeKQ==','SProjXodjZiK+xcXY/Xu/XDGWHcGmHo09Mr0mG6cRONExIGLg9k=','M93zjnfajzWfttqnvqXiAi8Mg/0WxvspSx4cPZLXEYx4Xc0wTYl3op6qMx76x1wxMP6r','I3NmcHDycyNHM4wvoN/tl1bM+/hb29Ad1a661t1h8wpnMT/m4WAvxphjxjvr4NqYgsgpc8Z2V7QJ40WFGU3+5eRj7HI=','Không','Kinh','single','92','900','31151',true,NOW(),NOW()) ON CONFLICT DO NOTHING;
INSERT INTO citizens (id,full_name,date_of_birth,gender,national_id,phone_number,email,permanent_address,religion,ethnicity,marital_status,province_code,district_code,ward_code,is_alive,created_at,updated_at)
VALUES (uuid_generate_v4(),'Đặng Thị Uyên','1955-03-22','female','UM7CHvPXm/ltsFyHjpdgZP5P/z2D3yOQ6MYutdsrhvOGtcTHdLkinQ==','aMs5mO2hNPKQeFHEAqgTBoBqxrMhTQ0p+orG7BFuJWpsVl3E/8c=','eEZm6RNPlwwhFxW36Ra4IBAB8oUTnbzBugUCotLGEhFsE+ydxGf1CdeYHwOnNRXmFHJi','OuRkCHDYQCHDWabtoaa8pd/LRUgI1t1Cn0NDg9DRM8RbLCPAz/zFEEtOMO8fF5qwXyaHZ8BKvLIFyVPO3go=','Phật giáo','Kinh','widowed','92','900','31150',false,NOW(),NOW()) ON CONFLICT DO NOTHING;
